name: Deploy Library Management System

on:
  push:
    branches:
      - main  # Trigger only on main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Build backend (if using TypeScript or Babel)
        working-directory: ./server
        run: |
          npm run build || echo "No build step for backend"

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Deploy placeholder step
        run: echo "✅ Replace this step with deployment to Render, Heroku, or another provider"
